#!/bin/bash
source .env

docker build \
  --build-arg VERSION=${VERSION} \
  --build-arg ELA_OC_AGENT_DEB=${ELA_OC_AGENT_DEB} \
  --build-arg ELA_OC_AGENT_SECRET=${ELA_OC_AGENT_SECRET} \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --build-arg VCS_REF=$(git rev-parse --short HEAD) \
  -t ${IMAGE_NAME} .
